aws:
  accessKey: AKIAXD4H34A2FZCTJ4UR
  secretKey: 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
  sns:
    arn: arn:aws:sns:ap-south-1:489374343220:mychannel
    sms:
      type:
        value: Promotional
      data:
        type: String

